Prepare for quiet release.

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -1,6 +1,5 @@
 # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
 # Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
-
 # Setup with usethis::use_github_action("test-coverage")
 # Then add
 # github::MatthewHeun/IEATools
@@ -12,52 +11,65 @@
 
 on:
   push:
-    branches: [main, master]
-  pull_request:
-    branches: [main, master]
-  schedule:
-    # Build main daily at 8 AM UTC, 3 AM EST, 4 AM EDT, one hour after nightly builds.
-    - cron: "0 8 * * *"
+  branches: [main, master]
+pull_request:
+  branches: [main, master]
+schedule:
+  # Build main daily at 8 AM UTC, 3 AM EST, 4 AM EDT, one hour after nightly builds.
+  - cron: "0 8 * * *"
 
-name: test-coverage
+name: test-coverage.yaml
+
+permissions: read-all
 
 jobs:
   test-coverage:
-    runs-on: ubuntu-latest
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  runs-on: ubuntu-latest
+env:
+  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
-    steps:
-      - uses: actions/checkout@v3
+steps:
+  - uses: actions/checkout@v4
 
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          use-public-rspm: true
+- uses: r-lib/actions/setup-r@v2
+with:
+  use-public-rspm: true
 
-      - uses: r-lib/actions/setup-r-dependencies@v2
-        with:
-          extra-packages: any::covr
-          needs: coverage
+- uses: r-lib/actions/setup-r-dependencies@v2
+with:
+  extra-packages: any::covr, any::xml2
+needs: coverage
 
-      - name: Test coverage
-        run: |
-          covr::codecov(
-            quiet = FALSE,
-            clean = FALSE,
-            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
-          )
-        shell: Rscript {0}
+- name: Test coverage
+run: |
+  cov <- covr::package_coverage(
+    quiet = FALSE,
+    clean = FALSE,
+    install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+  )
+print(cov)
+covr::to_cobertura(cov)
+shell: Rscript {0}
 
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+- uses: codecov/codecov-action@v4
+with:
+  # Fail if error if not on PR, or if on PR and token is given
+  fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
+file: ./cobertura.xml
+plugin: noop
+disable_search: true
+token: ${{ secrets.CODECOV_TOKEN }}
 
-      - name: Upload test results
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: coverage-test-failures
-          path: ${{ runner.temp }}/package
+- name: Show testthat output
+if: always()
+run: |
+  ## --------------------------------------------------------------------
+find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
+shell: bash
+
+- name: Upload test results
+if: failure()
+uses: actions/upload-artifact@v4
+with:
+  name: coverage-test-failures
+path: ${{ runner.temp }}/package
